### ISSUE TITLE
Add Company

### ISSUE THREAD

**Issue by CSCO-BOOT-23** [cscobootcamp/duncorp#4]
To add the Company name

**Comment by CSCO-BOOT-24** [comment]
new tag

**Comment by CSCO-BOOT-23** [comment]
Dun Corp is the company name.. ?

**Comment by CSCO-BOOT-23** [comment]
9/15-- we decided the company name as Dun Corp..

**Comment by CSCO-BOOT-23** [comment]
What do you think the Company is about
